"""Public immutable portfolio-domain API."""

from trading_bot.portfolio.exceptions import (
    InvalidOptimizationRequestError,
    InvalidOptimizationResultError,
    InvalidPortfolioConstraintsError,
    InvalidPortfolioStateError,
    InvalidReturnScenarioError,
    InvalidReturnScenarioSetError,
    InvalidTargetPortfolioError,
    PortfolioConstraintViolationError,
    PortfolioDomainError,
    PortfolioUniverseMismatchError,
    ScenarioCompatibilityError,
    ScenarioUniverseMismatchError,
)
from trading_bot.portfolio.models import (
    AllocationSource,
    ExpectedReturn,
    ForecastHorizon,
    MetadataEntry,
    OptimizationDiagnostic,
    OptimizationDiagnosticLevel,
    OptimizationStatus,
    PortfolioConstraints,
    PortfolioOptimizationRequest,
    PortfolioOptimizationResult,
    PortfolioPositionState,
    PortfolioState,
    TargetAllocation,
    TargetPortfolio,
)
from trading_bot.portfolio.optimizer import PortfolioOptimizer
from trading_bot.portfolio.scenarios import (
    ReturnScenario,
    ReturnScenarioSet,
    ScenarioSource,
)

__all__ = [
    "AllocationSource",
    "ExpectedReturn",
    "ForecastHorizon",
    "InvalidOptimizationRequestError",
    "InvalidOptimizationResultError",
    "InvalidPortfolioConstraintsError",
    "InvalidPortfolioStateError",
    "InvalidTargetPortfolioError",
    "InvalidReturnScenarioError",
    "InvalidReturnScenarioSetError",
    "MetadataEntry",
    "OptimizationDiagnostic",
    "OptimizationDiagnosticLevel",
    "OptimizationStatus",
    "PortfolioConstraintViolationError",
    "PortfolioConstraints",
    "PortfolioDomainError",
    "PortfolioOptimizationRequest",
    "PortfolioOptimizationResult",
    "PortfolioOptimizer",
    "PortfolioPositionState",
    "PortfolioState",
    "PortfolioUniverseMismatchError",
    "ReturnScenario",
    "ReturnScenarioSet",
    "ScenarioCompatibilityError",
    "ScenarioSource",
    "ScenarioUniverseMismatchError",
    "TargetAllocation",
    "TargetPortfolio",
]
