"""Public API for broker-independent order lifecycle management."""

from trading_bot.execution.engine import OrderEngine
from trading_bot.execution.exceptions import (
    DuplicateEventError,
    DuplicateFillError,
    DuplicateOrderError,
    FillMismatchError,
    InconsistentPaperSubmissionBatchResultError,
    InconsistentPaperSubmissionSourceError,
    InconsistentPortfolioOrderBatchResultError,
    InconsistentPortfolioOrderSourceError,
    InvalidEventTimeError,
    InvalidOrderTransitionError,
    InvalidPaperSubmissionBatchRequestError,
    InvalidPortfolioOrderBatchRequestError,
    InvalidRiskDecisionError,
    OrderEngineError,
    OrderNotFoundError,
    OverfillError,
    PaperOrderSubmissionError,
    PaperSubmissionEngineCopyError,
    PaperSubmissionEventCollisionError,
    PaperSubmissionOrchestrationError,
    PortfolioOrderCreationError,
    PortfolioOrderEngineCopyError,
    PortfolioOrderOrchestrationError,
)
from trading_bot.execution.models import (
    ExecutionInstruction,
    OrderEvent,
    OrderEventType,
)
from trading_bot.execution.paper_submission import (
    PaperOrderSubmitter,
    PaperSubmissionBatchRequest,
    PaperSubmissionBatchResult,
    PaperSubmissionBatchStatus,
    PaperSubmissionDiagnostic,
    PaperSubmissionDiagnosticCode,
)
from trading_bot.execution.portfolio_orders import (
    PortfolioOrderBatchRequest,
    PortfolioOrderBatchResult,
    PortfolioOrderBatchStatus,
    PortfolioOrderDiagnostic,
    PortfolioOrderDiagnosticCode,
    PortfolioOrderOrchestrator,
)

__all__ = [
    "DuplicateEventError",
    "DuplicateFillError",
    "DuplicateOrderError",
    "ExecutionInstruction",
    "FillMismatchError",
    "InconsistentPaperSubmissionBatchResultError",
    "InconsistentPaperSubmissionSourceError",
    "InconsistentPortfolioOrderBatchResultError",
    "InconsistentPortfolioOrderSourceError",
    "InvalidEventTimeError",
    "InvalidOrderTransitionError",
    "InvalidPaperSubmissionBatchRequestError",
    "InvalidPortfolioOrderBatchRequestError",
    "InvalidRiskDecisionError",
    "OrderEngine",
    "OrderEngineError",
    "OrderEvent",
    "OrderEventType",
    "OrderNotFoundError",
    "OverfillError",
    "PaperOrderSubmissionError",
    "PaperOrderSubmitter",
    "PaperSubmissionBatchRequest",
    "PaperSubmissionBatchResult",
    "PaperSubmissionBatchStatus",
    "PaperSubmissionDiagnostic",
    "PaperSubmissionDiagnosticCode",
    "PaperSubmissionEngineCopyError",
    "PaperSubmissionEventCollisionError",
    "PaperSubmissionOrchestrationError",
    "PortfolioOrderBatchRequest",
    "PortfolioOrderBatchResult",
    "PortfolioOrderBatchStatus",
    "PortfolioOrderCreationError",
    "PortfolioOrderDiagnostic",
    "PortfolioOrderDiagnosticCode",
    "PortfolioOrderEngineCopyError",
    "PortfolioOrderOrchestrationError",
    "PortfolioOrderOrchestrator",
]
