"""Public, Qt-free presentation contracts for the desktop GUI."""

from trading_bot.gui.evidence_timeline_adapter import build_evidence_timeline_state
from trading_bot.gui.evidence_timeline_models import (
    MAX_EVIDENCE_TIMELINE_ENTRIES,
    MAX_EVIDENCE_TIMELINE_IDENTIFIER_CHARACTERS,
    MAX_EVIDENCE_TIMELINE_TEXT_CHARACTERS,
    EvidenceTimelineEntry,
    EvidenceTimelinePageState,
    EvidenceTimelineSource,
)
from trading_bot.gui.market_data_models import (
    MAX_MARKET_DATA_MESSAGE_CHARACTERS,
    MAX_MARKET_DATA_PRESENTATION_TEXT_CHARACTERS,
    MAX_MARKET_DATA_SYMBOL_CHARACTERS,
    MAX_MARKET_DATA_SYMBOLS,
    MarketDataPageState,
    MarketDataPageStatus,
    VerifiedMarketSnapshotView,
    unavailable_market_data_state,
)
from trading_bot.gui.models import (
    ApplicationOverview,
    ComponentStatus,
    OperatingMode,
    PresentationStatus,
    ResearchComparisonState,
    ResearchPageState,
    ResearchReportStatus,
    ResearchReportView,
    ResearchResultRow,
    format_decimal_for_display,
    format_percentage_for_display,
)
from trading_bot.gui.operator_observability_models import (
    MAX_OPERATOR_ACCOUNT_ID_CHARACTERS,
    MAX_OPERATOR_CLASSIFICATION_CHARACTERS,
    MAX_OPERATOR_MESSAGE_CHARACTERS,
    MAX_OPERATOR_POSITIONS,
    MAX_OPERATOR_SYMBOL_CHARACTERS,
    OPERATOR_WARMUP_TARGET_COUNT,
    OperatorAccountPositionView,
    OperatorAccountSummaryView,
    OperatorEffectGateState,
    OperatorObservabilityState,
    OperatorOperationsPageState,
    OperatorOperationsPageStatus,
    OperatorWarmupClassification,
    OperatorWarmupView,
    SelectedC3WarmupSessionView,
    unavailable_operator_operations_state,
)
from trading_bot.gui.paper_account_models import (
    MAX_PAPER_ACCOUNT_MESSAGE_CHARACTERS,
    MAX_PAPER_ACCOUNT_POSITIONS,
    MAX_PAPER_ACCOUNT_SYMBOL_CHARACTERS,
    PaperAccountCheckpointKindView,
    PaperAccountPageState,
    PaperAccountPageStatus,
    PaperAccountPositionView,
    VerifiedPaperAccountView,
    unavailable_paper_account_state,
)
from trading_bot.gui.paper_inspection_service import PaperOperationInspectionService
from trading_bot.gui.paper_models import (
    MAX_PAPER_RECEIPT_PATH_CHARACTERS,
    PaperInspectionClassification,
    PaperInspectionDiagnostic,
    PaperOperationInspectionView,
    PaperPageState,
    PaperPageStatus,
    unavailable_paper_state,
)
from trading_bot.gui.research_service import CompactReportResearchService
from trading_bot.gui.services import GuiApplicationService, ResearchReportLoader
from trading_bot.gui.startup_composition import (
    GuiStartupConfiguration,
    ReadOnlyGuiApplicationService,
)
from trading_bot.gui.system_health_adapter import build_system_health_state
from trading_bot.gui.system_health_models import (
    MAX_SYSTEM_AUDIT_ENTRIES,
    MAX_SYSTEM_COMPONENTS,
    MAX_SYSTEM_IDENTIFIER_CHARACTERS,
    MAX_SYSTEM_TEXT_CHARACTERS,
    SystemAuditEntryView,
    SystemComponentHealthView,
    SystemComponentStatus,
    SystemHealthPageState,
    SystemHealthStatus,
)
from trading_bot.gui.verified_genesis_paper_account_inspection_service import (
    VerifiedGenesisPaperAccountInspectionService,
)
from trading_bot.gui.verified_snapshot_inspection_service import (
    VerifiedSnapshotInspectionService,
)
from trading_bot.gui.verified_successor_paper_account_inspection_service import (
    VerifiedSuccessorPaperAccountInspectionService,
)

__all__ = [
    "ApplicationOverview",
    "ComponentStatus",
    "CompactReportResearchService",
    "EvidenceTimelineEntry",
    "EvidenceTimelinePageState",
    "EvidenceTimelineSource",
    "GuiApplicationService",
    "GuiStartupConfiguration",
    "MAX_EVIDENCE_TIMELINE_ENTRIES",
    "MAX_EVIDENCE_TIMELINE_IDENTIFIER_CHARACTERS",
    "MAX_EVIDENCE_TIMELINE_TEXT_CHARACTERS",
    "MAX_MARKET_DATA_MESSAGE_CHARACTERS",
    "MAX_MARKET_DATA_PRESENTATION_TEXT_CHARACTERS",
    "MAX_MARKET_DATA_SYMBOL_CHARACTERS",
    "MAX_MARKET_DATA_SYMBOLS",
    "MAX_PAPER_ACCOUNT_MESSAGE_CHARACTERS",
    "MAX_PAPER_ACCOUNT_POSITIONS",
    "MAX_PAPER_ACCOUNT_SYMBOL_CHARACTERS",
    "MAX_OPERATOR_ACCOUNT_ID_CHARACTERS",
    "MAX_OPERATOR_CLASSIFICATION_CHARACTERS",
    "MAX_OPERATOR_MESSAGE_CHARACTERS",
    "MAX_OPERATOR_POSITIONS",
    "MAX_OPERATOR_SYMBOL_CHARACTERS",
    "OPERATOR_WARMUP_TARGET_COUNT",
    "MAX_PAPER_RECEIPT_PATH_CHARACTERS",
    "MAX_SYSTEM_AUDIT_ENTRIES",
    "MAX_SYSTEM_COMPONENTS",
    "MAX_SYSTEM_IDENTIFIER_CHARACTERS",
    "MAX_SYSTEM_TEXT_CHARACTERS",
    "MarketDataPageState",
    "MarketDataPageStatus",
    "OperatingMode",
    "OperatorAccountPositionView",
    "OperatorAccountSummaryView",
    "OperatorEffectGateState",
    "OperatorObservabilityState",
    "OperatorOperationsPageState",
    "OperatorOperationsPageStatus",
    "OperatorWarmupClassification",
    "OperatorWarmupView",
    "SelectedC3WarmupSessionView",
    "PaperAccountCheckpointKindView",
    "PaperAccountPageState",
    "PaperAccountPageStatus",
    "PaperAccountPositionView",
    "PaperInspectionClassification",
    "PaperInspectionDiagnostic",
    "PaperOperationInspectionView",
    "PaperOperationInspectionService",
    "PaperPageState",
    "PaperPageStatus",
    "PresentationStatus",
    "ResearchComparisonState",
    "ResearchPageState",
    "ResearchReportStatus",
    "ResearchReportView",
    "ResearchResultRow",
    "ResearchReportLoader",
    "SystemAuditEntryView",
    "SystemComponentHealthView",
    "SystemComponentStatus",
    "SystemHealthPageState",
    "SystemHealthStatus",
    "ReadOnlyGuiApplicationService",
    "VerifiedMarketSnapshotView",
    "VerifiedPaperAccountView",
    "VerifiedGenesisPaperAccountInspectionService",
    "VerifiedSnapshotInspectionService",
    "VerifiedSuccessorPaperAccountInspectionService",
    "build_evidence_timeline_state",
    "build_system_health_state",
    "format_decimal_for_display",
    "format_percentage_for_display",
    "unavailable_market_data_state",
    "unavailable_operator_operations_state",
    "unavailable_paper_account_state",
    "unavailable_paper_state",
]
